/** Holds the Configuration of the Data elements class **/
#include "../headers/DataElementsConfig.h"

const std::vector<DataElementsConfig> dataElementsConfig {
        DataElementsConfig(2, "PAN", 19, VARIABLETYPE::VARIABLE,FIELDFORMAT::LLVAR),
        DataElementsConfig(3, "ProcCode", 6),
        DataElementsConfig(4, "Transaction Amount", 12),
        DataElementsConfig(5, "Settlement Amount", 12),
        DataElementsConfig(6, "Cardholder Billing Amount", 0 ),
        DataElementsConfig(7, "Time", 10),
        DataElementsConfig(8, "", 0),
        DataElementsConfig(9, "Rate", 8),
        DataElementsConfig(10, "", 0),
        DataElementsConfig(11, "STAN", 6),
        DataElementsConfig(12, "OrigTime", 6), /*Hhmmss*/
        DataElementsConfig(13, "OrigDate", 4), /*MMDD*/
        DataElementsConfig(14, "ExpireDate", 4), /*YYMM*/
        DataElementsConfig(15, "", 4), /*MMDD*/
        DataElementsConfig(16, "", 4), /*MMDD*/
        DataElementsConfig(17, "", 0), /*MMDD*/
        DataElementsConfig(18, "TermSic", 4),
        DataElementsConfig(19, "", 0),
        DataElementsConfig(20, "", 0),
        DataElementsConfig(21, "", 0),
        DataElementsConfig(22, "PosEntryMode", 3),
        DataElementsConfig(23, "CardMember", 3),
        DataElementsConfig(24, "", 0),
        DataElementsConfig(25, "PosCondition", 2),
        DataElementsConfig(26, "PinCaptureCode", 2),
        DataElementsConfig(27, "", 0),
        CheckXType(28, "AcqFee", 8, VARIABLETYPE::FIXED, FIELDFORMAT::NONE,TRANSACTIONMODE::DEBIT), /** we need to find algorithm or way to figure out if its a debit or credit**/
        CheckXType(29, "SettleFee", 8,  VARIABLETYPE::FIXED, FIELDFORMAT::NONE,TRANSACTIONMODE::DEBIT),
        CheckXType(30, "TransProcessingFee", 8,  VARIABLETYPE::FIXED, FIELDFORMAT::NONE,TRANSACTIONMODE::DEBIT ),
        CheckXType(31, "SettleProcessingFee", 8,  VARIABLETYPE::FIXED, FIELDFORMAT::NONE,TRANSACTIONMODE::DEBIT ),
        DataElementsConfig(32, "TermInstId", 11, VARIABLETYPE::VARIABLE, FIELDFORMAT::LLVAR),
        DataElementsConfig(33, "", 11, VARIABLETYPE::VARIABLE, FIELDFORMAT::LLVAR), /******************** the Name?? **/
        DataElementsConfig(34, "", 0),
        DataElementsConfig(35, "Track2", 37, VARIABLETYPE::VARIABLE, FIELDFORMAT::LLVAR),
        DataElementsConfig(36, "", 0),
        DataElementsConfig(37, "TranNumber", 12 ),
        DataElementsConfig(38, " AuthorizationCode", 6),
        DataElementsConfig(39, "ResponseCode", 2),
        DataElementsConfig(40, "ServiceCode", 3),
        DataElementsConfig(41, "TerminalId", 8),
        DataElementsConfig(42, "MerchantId", 15),
        DataElementsConfig(43, "TermInfo", 40),
        DataElementsConfig(44, "ResponseData", 25, VARIABLETYPE::VARIABLE, FIELDFORMAT::LLVAR),
        DataElementsConfig(45,"Track1", 76, VARIABLETYPE::VARIABLE, FIELDFORMAT::LLVAR),
        DataElementsConfig(46, "", 0),
        DataElementsConfig(47, "", 0),
        DataElementsConfig(48, "AdditionalData", 999, VARIABLETYPE::VARIABLE, FIELDFORMAT::LLVAR),
        DataElementsConfig(49, "Currency", 3),
        DataElementsConfig(50, "CurrencyCode", 3),
        DataElementsConfig(51, "", 0),
        DataElementsConfig(52, "Pin data", 16),
        DataElementsConfig(53, "", 96), /********************** the Name?? **/
        DataElementsConfig(54, "Additional Amounts",120, VARIABLETYPE::VARIABLE, FIELDFORMAT::LLLVAR),
        DataElementsConfig(55, "", 510, VARIABLETYPE::VARIABLE, FIELDFORMAT::LLLVAR), /************ the Name?? **/
        DataElementsConfig(56, "Message Reason Code", 4, VARIABLETYPE::VARIABLE, FIELDFORMAT::LLLVAR),
        DataElementsConfig(57, "", 0),
        DataElementsConfig(58, "Authorizing Agent Code", 11,VARIABLETYPE::VARIABLE, FIELDFORMAT::LLLVAR),
        DataElementsConfig(59, "Echo Data", 255, VARIABLETYPE::VARIABLE, FIELDFORMAT::LLLVAR),
        DataElementsConfig(60, "Payment Information", 999, VARIABLETYPE::VARIABLE, FIELDFORMAT::LLLVAR),
        DataElementsConfig(61, "", 0),
        DataElementsConfig(62, "ExtratranAttr", 999, VARIABLETYPE::VARIABLE, FIELDFORMAT::LLLVAR),
        DataElementsConfig(63, "ExtratranAttr2", 999, VARIABLETYPE::VARIABLE, FIELDFORMAT::LLLLVAR),
        DataElementsConfig(64, " Primary Message Hash Value", 64, VARIABLETYPE::FIXED, FIELDFORMAT::AN),
        DataElementsConfig(65, "", 0),
        DataElementsConfig(66, "", 0),
        DataElementsConfig(67, "Extended Payment Code", 2),
        DataElementsConfig(68, "", 0),
        DataElementsConfig(69, "", 0),
        DataElementsConfig(70, "Net", 9),
        DataElementsConfig(71, "", 0),
        DataElementsConfig(72, "", 0),
        DataElementsConfig(73, "", 0),
        DataElementsConfig(74, "", 0),
        DataElementsConfig(75, "", 0),
        DataElementsConfig(76, "", 0),
        DataElementsConfig(77, "", 0),
        DataElementsConfig(78, "", 0),
        DataElementsConfig(79, "", 0),
        DataElementsConfig(80, "", 0),
        DataElementsConfig(81, "", 0),
        DataElementsConfig(82, "", 0),
        DataElementsConfig(83, "", 0),
        DataElementsConfig(84, "", 0),
        DataElementsConfig(85, "", 0),
        DataElementsConfig(86, "", 0),
        DataElementsConfig(87, "", 0),
        DataElementsConfig(88, "", 0),
        DataElementsConfig(89, "", 0),
        DataElementsConfig(90, "Payee", 42),
        DataElementsConfig(91, "", 0),
        DataElementsConfig(92, "", 0),
        DataElementsConfig(93, "", 0),
        DataElementsConfig(94, "", 0),
        DataElementsConfig(95, "Replacement Amounts", 42),
        DataElementsConfig(96, "", 0),
        DataElementsConfig(97, "", 0),
        DataElementsConfig(98, "Payee", 25),
        DataElementsConfig(99, "", 0),
        DataElementsConfig(100, " Receiving Institution ID Code", 11, VARIABLETYPE::VARIABLE, FIELDFORMAT::LLVAR),
        DataElementsConfig(101, "", 0),
        DataElementsConfig(102, " Account Identification 1", 28, VARIABLETYPE::VARIABLE, FIELDFORMAT::LLVAR),
        DataElementsConfig(103, "To Account", 28, VARIABLETYPE::VARIABLE, FIELDFORMAT::LLVAR),
        DataElementsConfig(104, "", 0),
        DataElementsConfig(105, "", 0),
        DataElementsConfig(106, "", 0),
        DataElementsConfig(107, "", 0),
        DataElementsConfig(108, "", 0),
        DataElementsConfig(109, "", 0),
        DataElementsConfig(110, "", 0),
        DataElementsConfig(111, "", 0),
        DataElementsConfig(112, "", 0),
        DataElementsConfig(113, "", 0),
        DataElementsConfig(114, "", 0),
        DataElementsConfig(115, "", 0),
        DataElementsConfig(116, "", 0),
        DataElementsConfig(117, "", 0),
        DataElementsConfig(118, "", 0),
        DataElementsConfig(119, "", 0),
        DataElementsConfig(120, "", 0),
        DataElementsConfig(121, "", 0),
        DataElementsConfig(122, "", 0),
        DataElementsConfig(123, "PosDataCode>", 15, VARIABLETYPE::FIXED, FIELDFORMAT::LLLVAR),
        DataElementsConfig(124, " Near Field Communication Data", 9999,VARIABLETYPE::VARIABLE,  FIELDFORMAT::LLLLVAR),
        DataElementsConfig(125, "", 0),
        DataElementsConfig(126, "", 0),
        DataElementsConfig(127, "", 0),
        DataElementsConfig(128, "", 64, VARIABLETYPE::FIXED, FIELDFORMAT::AN)
};


